import OpenAI from "openai";
import { z } from "zod";
import { ParsedAuditSchema } from "./audit-schema";
import type { ParsedAudit } from "./audit-schema";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const MINI_MODEL = process.env.OPENAI_AUDIT_MINI_MODEL ?? "gpt-4o-mini";
const FULL_MODEL = process.env.OPENAI_MODEL ?? "gpt-4o";

// ─── Prompt ───────────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are parsing a UNH (University of New Hampshire) degree audit document generated by Ellucian Degree Works.

Extract three lists of courses from the audit:

1. remaining_courses: courses the student STILL NEEDS to take
2. in_progress_courses: courses marked "IP" (currently being taken this semester)
3. completed_courses: courses already finished (have a letter grade A/B/C/D/F, CR, or TCR)

RULES for remaining_courses:
- Include courses where you see "Still needed: 1 Class in SUBJ NNN"
- SKIP anything with a letter grade, CR, TCR, or IP
- For OR choices like "HMGT 405 or NUTR 403": create ONE entry using the first option's subject/number, title should list both e.g. "Intro to Food Service Mgt (HMGT 405 or NUTR 403)"
- For level/range requirements like "1 Class in @ 600:799 with attribute = WRIT": use subject "DISC_REQ", number "WRIT_600", title "Upper-level Writing Intensive (600-799 level)", credits 4
- For "1 Class in @ @ with attribute = INQ": use subject "DISC_REQ", number "INQ", title "Inquiry Requirement", credits 4
- For "4 Credits in ECOG 701": use subject "ECOG", number "701", credits 4
- Credits: UNH courses are typically 4 credits. Use 4 as the default unless stated otherwise (e.g. 1-credit seminars).

RULES for Discovery Program (Gen-Ed) remaining requirements:
UNH uses a "Discovery Program" with named categories. Each category has an attribute code.
A category is STILL NEEDED if it shows "Still needed: 1 Class in @ @ with attribute = XX"
A category is DONE if it has a completed course listed under it with a grade.

For each NOT COMPLETE Discovery Program requirement:
- Create ONE entry with subject "DISC_REQ" and number = the attribute code
- Use the category name as the title (e.g. "Physical Science Category")
- credits: 4 (default for UNH Discovery courses)
- requirement_category: "General Education"

Known UNH Discovery Program attribute codes:
- INQ (Inquiry Requirement)
- DLAB (Biological or Physical Science Laboratory)
- PS (Physical Science)
- HP (Historical Perspectives)
- WC (World Cultures)
- FPA (Fine & Performing Arts) — look for "Fine & Performing Arts Category"
- ETS (Environment, Technology & Society) — look for "Environment, Technology & Society Category"
- BIOL (Biological Science) — look for "Biological Science Category"
- HUM (Humanities) — look for "Humanities Category"
- SS (Social Sciences) — look for "Social Sciences Category"
- WRIT (Writing Intensive) — for Writing Intensive requirements without a specific course

For writing requirements:
- "Writing Intensive in [Major]" with a specific course (e.g. ECOG 701) → use that specific course, subject "ECOG" number "701"
- "Upper-level Writing Intensive: 1 Class in @ 600:799 with attribute = WRIT" → use subject "DISC_REQ" number "WRIT_600", title "Upper-level Writing Intensive"

RULES for in_progress_courses:
- Include ALL courses marked "IP" — currently being taken, should NOT be scheduled again
- Use the semester shown (Spring 2026, Summer 2026) — include all

RULES for completed_courses:
- Include ALL courses with letter grades (A, A-, B+, B, etc.), CR (credit), or TCR (transfer credit)
- Include the subject and course number so prereq checking works

Return ONLY valid JSON:
{
  "remaining_courses": [
    {
      "subject": "FIN",
      "number": "701",
      "title": "Financial Policy",
      "credits": 4,
      "requirement_category": "Major Core"
    },
    {
      "subject": "DISC_REQ",
      "number": "PS",
      "title": "Physical Science Category",
      "credits": 4,
      "requirement_category": "General Education"
    }
  ],
  "in_progress_courses": [
    {
      "subject": "ADMN",
      "number": "503",
      "title": "Managerial Accounting",
      "credits": 4
    }
  ],
  "completed_courses": [
    {
      "subject": "ECON",
      "number": "401",
      "title": "Principles of Economics Macro",
      "credits": 4
    }
  ],
  "student_name": "string or null",
  "major": "string or null",
  "credits_completed": number or null,
  "credits_remaining": number or null
}

requirement_category must be one of: "Major Core", "Major Elective", "General Education", "Free Elective", "Other"`;

// ─── Quality Check ────────────────────────────────────────────────────────────

function checkQuality(data: ParsedAudit): { ok: boolean; reason?: string } {
  if (data.remaining_courses.length === 0) {
    return { ok: false, reason: "no remaining courses extracted" };
  }
  const badCourse = data.remaining_courses.find((c) => !c.subject || !c.number);
  if (badCourse) {
    return { ok: false, reason: `course missing subject/number: ${JSON.stringify(badCourse)}` };
  }
  if (data.completed_courses.length === 0 && data.in_progress_courses.length === 0) {
    return { ok: false, reason: "no completed or in-progress courses — likely incomplete parse" };
  }
  return { ok: true };
}

// ─── Single Model Call ────────────────────────────────────────────────────────

async function callModel(
  model: string,
  pdfText: string
): Promise<{ data: ParsedAudit; usage: OpenAI.CompletionUsage | null }> {
  const response = await openai.chat.completions.create({
    model,
    temperature: 0,
    response_format: { type: "json_object" },
    max_tokens: 3000,
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: pdfText },
    ],
  });

  const raw = response.choices[0].message.content ?? "";
  const cleaned = raw.replace(/```json|```/g, "").trim();

  let json: unknown;
  try {
    json = JSON.parse(cleaned);
  } catch {
    throw new Error(`Model returned non-JSON: ${cleaned.slice(0, 200)}`);
  }

  const data = ParsedAuditSchema.parse(json);
  return { data, usage: response.usage ?? null };
}

// ─── Public API ───────────────────────────────────────────────────────────────

export interface AuditParseResult {
  data: ParsedAudit;
  model: string;
  fallback: boolean;
  latencyMs: number;
  usage: OpenAI.CompletionUsage | null;
}

export async function parseUnhAudit(pdfText: string): Promise<AuditParseResult> {
  const start = Date.now();

  // First pass: cheap model
  try {
    const { data, usage } = await callModel(MINI_MODEL, pdfText);
    const quality = checkQuality(data);

    if (quality.ok) {
      const latencyMs = Date.now() - start;
      console.log(
        `[unh-audit-parser] mini OK | model=${MINI_MODEL} | remaining=${data.remaining_courses.length} | latency=${latencyMs}ms`
      );
      return { data, model: MINI_MODEL, fallback: false, latencyMs, usage };
    }

    console.warn(
      `[unh-audit-parser] mini quality fail | reason="${quality.reason}" — falling back`
    );
  } catch (err) {
    const reason = err instanceof z.ZodError
      ? `schema: ${err.issues.map((i) => `${i.path.join(".")} ${i.message}`).join(", ")}`
      : err instanceof Error ? err.message : String(err);
    console.warn(`[unh-audit-parser] mini error | reason="${reason}" — falling back`);
  }

  // Fallback: full model
  const { data, usage } = await callModel(FULL_MODEL, pdfText);
  const latencyMs = Date.now() - start;
  console.log(
    `[unh-audit-parser] fallback OK | model=${FULL_MODEL} | remaining=${data.remaining_courses.length} | latency=${latencyMs}ms`
  );
  return { data, model: FULL_MODEL, fallback: true, latencyMs, usage };
}
